### ISSUE TITLE
100% CPU usage on MacOS, due to PolyML bug :(

### ISSUE THREAD

**Issue by KidkArolis** [KidkArolis/PolyChrome#1]

**Comment by iislucas** [comment]
bug reported to ML list: 
http://lists.inf.ed.ac.uk/mailman/private/polyml/2011-January/000811.html

**Comment by KidkArolis** [comment]
fixed in PolyML fixes-5.4 version

**Comment by iislucas** [comment]
Currently fixed in PolyML svn; but will be pushed back to 5.4-fixes soon.

**Comment by iislucas** [comment]
fix was pushed back to 5.4-fixes; I've just tested it and it works.
